Scenario Result
SpaceStock/go-restify pull request #3
Opened 2020-01-31 07:59 UTC by hugoiman

PR: change return []TestCase to ScenarioResult in func Run()

2020-01-31 09:43 UTC, bastianrob requested changes

2020-01-31 09:43 UTC, bastianrob commented on scenario/scenario.go
> +	sr.IsFailed()
kenapa manggil `.IsFailed()` disini??

2020-01-31 09:44 UTC, hugoiman commented on scenario/scenario.go
> +	sr.IsFailed()
oiyak lupa di apus

2020-01-31 09:49 UTC, bastianrob requested changes

2020-01-31 09:49 UTC, bastianrob commented on scenario/scenario.go
> +	sr := restify.ScenarioResult(testResults)
Ini juga sebernya gak perlu di tampung ke `sr` langsung aja `return restify.ScenarioResult(testResults)`

2020-01-31 09:50 UTC, bastianrob requested changes

2020-01-31 09:50 UTC, bastianrob commented on result.go
> +		if tc.Success == false {
`if !tc.Success`

2020-01-31 10:13 UTC, bastianrob requested changes

2020-01-31 10:13 UTC, bastianrob commented on result.go
> +//IsFailed is
IsFailed is what?
Please give a proper comment

2020-01-31 10:13 UTC, bastianrob commented on result.go
> +//ScenarioResult is
ScenarioResult is what?
Please give a proper comment

2020-01-31 10:14 UTC, bastianrob commented
@hugoiman

2020-01-31 10:15 UTC, bastianrob commented
Anyway ini juga kenapa masih di branch `feature/time-delay` ya

2020-02-03 02:11 UTC, bastianrob approved these changes

2020-02-03 02:12 UTC, merged